// secret-map.mjs — the canonical secret-id -> env-var table used to hydrate a session.
//
// WHY IT IS ITS OWN MODULE (2026-08-18): setup/fetch-secrets-azure.mjs carried this table inline,
// and setup/fetch-secrets-aws.mjs needs the exact same one. Two hand-maintained copies of a
// 98-row mapping is a drift bug waiting to happen -- add a secret to one hydrator and it silently
// never reaches a session hydrated by the other. This module is the single copy; the Azure
// hydrator keeps its inline literal for now, and tests/secret-map-parity.test.mjs fails the build
// if the two ever disagree, so the drift cannot land unnoticed.
//
// Fields are exactly as the Azure hydrator defines them:
//   id       the secret name, identical in AWS SSM (/otchealth/<id>) and Azure Key Vault
//   env      the environment variable the value is exported as
//   required if true, a hydrator reports a MISSING error and exits non-zero when it is absent
//
// PEM / multiline / binary secrets are deliberately ABSENT from this table: they would corrupt the
// flat credentials.env. Materialize those on demand with setup/get-secret.mjs <id> <outfile>.

export const MAP = [
  { id: "openai-api-key", env: "OPENAI_API_KEY", required: true },
  { id: "elevenlabs-api-key", env: "ELEVENLABS_API_KEY", required: true },
  { id: "recraft-api-key", env: "RECRAFT_API_KEY", required: false },
  { id: "azure-openai-endpoint", env: "AZURE_OPENAI_ENDPOINT", required: false },
  { id: "azure-openai-key", env: "AZURE_OPENAI_API_KEY", required: false },
  { id: "azure-openai-api-version", env: "AZURE_OPENAI_API_VERSION", required: false },
  { id: "azure-openai-image-deployment", env: "AZURE_OPENAI_IMAGE_DEPLOYMENT", required: false },
  { id: "azure-openai-vision-deployment", env: "AZURE_OPENAI_VISION_DEPLOYMENT", required: false },
  { id: "azure-openai-video-deployment", env: "AZURE_OPENAI_VIDEO_DEPLOYMENT", required: false },
  { id: "azure-speech-key", env: "AZURE_SPEECH_KEY", required: false },
  { id: "azure-speech-region", env: "AZURE_SPEECH_REGION", required: false },
  { id: "azure-sp-client-id", env: "AZURE_SP_CLIENT_ID", required: false },
  { id: "azure-sp-client-secret", env: "AZURE_SP_CLIENT_SECRET", required: false },
  { id: "azure-sp-tenant-id", env: "AZURE_SP_TENANT_ID", required: false },
  { id: "azure-subscription-id", env: "AZURE_SUBSCRIPTION_ID", required: false },
  { id: "depot-token", env: "DEPOT_TOKEN", required: false },
  { id: "depot-project-id", env: "DEPOT_PROJECT_ID", required: false },
  { id: "posthog-personal-api-key", env: "POSTHOG_PERSONAL_API_KEY", required: false },
  { id: "posthog-host", env: "POSTHOG_HOST", required: false },
  { id: "miro-token", env: "MIRO_TOKEN", required: false },
  { id: "miro-client-id", env: "MIRO_CLIENT_ID", required: false },
  { id: "miro-client-secret", env: "MIRO_CLIENT_SECRET", required: false },
  { id: "make-api-token", env: "MAKE_API_TOKEN", required: false },
  { id: "daytona-api-key", env: "DAYTONA_API_KEY", required: false },
  { id: "daytona-api-url", env: "DAYTONA_API_URL", required: false },
  { id: "greptile-token", env: "GREPTILE_TOKEN", required: false },
  { id: "replicate-api-token", env: "REPLICATE_API_TOKEN", required: false },
  { id: "n8n-api-key", env: "N8N_API_KEY", required: false },
  { id: "n8n-base-url", env: "N8N_BASE_URL", required: false },
  { id: "sentry-auth-token", env: "SENTRY_AUTH_TOKEN", required: false },
  { id: "cloudflare-api-token", env: "CLOUDFLARE_API_TOKEN", required: false },
  { id: "netlify-token", env: "NETLIFY_TOKEN", required: false },
  { id: "railway-token", env: "RAILWAY_TOKEN", required: false },
  { id: "amzn-lwa-client-id", env: "AMZ_LWA_CLIENT_ID", required: false },
  { id: "amzn-lwa-client-secret", env: "AMZ_LWA_CLIENT_SECRET", required: false },
  { id: "amzn-sp-refresh-token", env: "AMZ_SP_REFRESH_TOKEN", required: false },
  { id: "amzn-seller-id", env: "AMZ_SELLER_ID", required: false },
  { id: "plaid-client-id", env: "PLAID_CLIENT_ID", required: false },
  { id: "plaid-secret", env: "PLAID_SECRET", required: false },
  { id: "plaid-env", env: "PLAID_ENV", required: false },
  { id: "massive-api-key", env: "MASSIVE_API_KEY", required: false },
  { id: "massive-api-key-2", env: "MASSIVE_API_KEY_2", required: false },
  { id: "azure-cfo-storage-account", env: "AZURE_STORAGE_ACCOUNT", required: false },
  { id: "azure-cfo-storage-container", env: "AZURE_STORAGE_CONTAINER", required: false },
  { id: "azure-cfo-storage-key", env: "AZURE_STORAGE_KEY", required: false },
  { id: "azure-commerce-storage-account", env: "AZURE_COMMERCE_STORAGE_ACCOUNT", required: false },
  { id: "azure-commerce-storage-key", env: "AZURE_COMMERCE_STORAGE_KEY", required: false },
  { id: "azure-commons-storage-account", env: "AZURE_COMMONS_STORAGE_ACCOUNT", required: false },
  { id: "azure-commons-storage-key", env: "AZURE_COMMONS_STORAGE_KEY", required: false },
  { id: "azure-docintel-endpoint", env: "AZURE_DOCINTEL_ENDPOINT", required: false },
  { id: "azure-docintel-key", env: "AZURE_DOCINTEL_KEY", required: false },
  { id: "azure-search-endpoint", env: "AZURE_SEARCH_ENDPOINT", required: false },
  { id: "azure-search-admin-key", env: "AZURE_SEARCH_KEY", required: false },
  { id: "azure-openai-embedding-deployment", env: "AZURE_OPENAI_EMBEDDING_DEPLOYMENT", required: false },
  { id: "azure-foundry-endpoint", env: "AZURE_FOUNDRY_ENDPOINT", required: false },
  { id: "azure-foundry-key", env: "AZURE_FOUNDRY_KEY", required: false },
  { id: "azure-foundry-gen-deployment", env: "AZURE_FOUNDRY_GEN_DEPLOYMENT", required: false },
  { id: "azure-legal-storage-account", env: "AZURE_LEGAL_STORAGE_ACCOUNT", required: false },
  { id: "azure-legal-storage-key", env: "AZURE_LEGAL_STORAGE_KEY", required: false },
  { id: "legal-courtlistener-token", env: "LEGAL_COURTLISTENER_TOKEN", required: false },
  { id: "govinfo-api-key", env: "GOVINFO_API_KEY", required: false },
  { id: "gmail-oauth-client-id", env: "GMAIL_OAUTH_CLIENT_ID", required: false },
  { id: "gmail-oauth-client-secret", env: "GMAIL_OAUTH_CLIENT_SECRET", required: false },
  { id: "gmail-refresh-token", env: "GMAIL_REFRESH_TOKEN", required: false },
  { id: "graph-sites-client-id", env: "GRAPH_SITES_CLIENT_ID", required: false },
  { id: "graph-sites-client-secret", env: "GRAPH_SITES_CLIENT_SECRET", required: false },
  { id: "context7-api-key", env: "CONTEXT7_API_KEY", required: false },
  { id: "datadog-api-key", env: "DD_API_KEY", required: false },
  { id: "datadog-app-key", env: "DD_APP_KEY", required: false },
  { id: "datadog-site", env: "DD_SITE", required: false },
  { id: "qbo-client-id", env: "QBO_CLIENT_ID", required: false },
  { id: "qbo-client-secret", env: "QBO_CLIENT_SECRET", required: false },
  { id: "qbo-env", env: "QBO_ENV", required: false },
  { id: "qbo-realm-otchealth", env: "QBO_REALM_OTCHEALTH", required: false },
  { id: "qbo-refresh-otchealth", env: "QBO_REFRESH_OTCHEALTH", required: false },
  { id: "qbo-realm-innd", env: "QBO_REALM_INND", required: false },
  { id: "qbo-refresh-innd", env: "QBO_REFRESH_INND", required: false },
  { id: "qbo-realm-hearingassist", env: "QBO_REALM_HEARINGASSIST", required: false },
  { id: "qbo-refresh-hearingassist", env: "QBO_REFRESH_HEARINGASSIST", required: false },
  { id: "qbo-realm-personal", env: "QBO_REALM_PERSONAL", required: false },
  { id: "qbo-refresh-personal", env: "QBO_REFRESH_PERSONAL", required: false },
  { id: "xero-client-id", env: "XERO_CLIENT_ID", required: false },
  { id: "xero-client-secret", env: "XERO_CLIENT_SECRET", required: false },
  { id: "xero-refresh-token", env: "XERO_REFRESH_TOKEN", required: false },
  { id: "xero-refresh-token-otchealth", env: "XERO_REFRESH_TOKEN_OTCHEALTH", required: false },
  { id: "xero-refresh-token-innd", env: "XERO_REFRESH_TOKEN_INND", required: false },
  { id: "xero-refresh-token-hearingassist", env: "XERO_REFRESH_TOKEN_HEARINGASSIST", required: false },
  { id: "xero-refresh-token-personal", env: "XERO_REFRESH_TOKEN_PERSONAL", required: false },
  { id: "graph-mail-client-id", env: "GRAPH_MAIL_CLIENT_ID", required: false },
  { id: "graph-mail-client-secret", env: "GRAPH_MAIL_CLIENT_SECRET", required: false },
  { id: "graph-mail-tenant-id", env: "GRAPH_MAIL_TENANT_ID", required: false },
  { id: "github-app-id", env: "GITHUB_APP_ID", required: false },
  { id: "github-app-client-id", env: "GITHUB_APP_CLIENT_ID", required: false },
  { id: "github-app-installation-id", env: "GITHUB_APP_INSTALLATION_ID", required: false },
  { id: "cfo-source-bucket", env: "CFO_SOURCE_BUCKET", required: false },
  { id: "fourvault-gemini-api-key", env: "FOURVAULT_GEMINI_API_KEY", required: false },
  { id: "fourvault-neon-database-url", env: "FOURVAULT_NEON_DATABASE_URL", required: false },
  { id: "fourvault-neon-database-url-direct", env: "FOURVAULT_NEON_DATABASE_URL_DIRECT", required: false },
];
