#!/usr/bin/env bash
# session-start.sh — installs the OTCHealth designer skill into ~/.claude/skills
# and re-hydrates credentials from environment secrets. Idempotent: safe to run
# at the start of every Claude Code (web) session.
#
# Wire this into each project's Claude Code environment setup script, e.g.:
#   git clone https://github.com/gbgolfmatt/otchealth-claude-tools /tmp/octools \
#     2>/dev/null || (cd /tmp/octools && git pull --ff-only)
#   bash /tmp/octools/setup/session-start.sh
#
# Secrets model: ONE environment secret bootstraps everything.
#   GCP_CLAUDE_DRIVER_SA_JSON  full JSON of the non-PHI claude-driver SA key
# Using that SA, this script pulls the API keys from GCP Secret Manager
# (secrets: openai-api-key, elevenlabs-api-key, optional recraft-api-key).
# OPENAI_API_KEY / ELEVENLABS_API_KEY may still be passed directly as env
# vars to override Secret Manager (useful for local dev).
# Optional:
#   GOOGLE_CLOUD_PROJECT (default otchealth-shared-prod),
#   VERTEX_DEFAULT_IMAGEN_MODEL / _VIDEO_MODEL / _LLM_MODEL

set -euo pipefail

TOOLS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SKILLS_DST="${HOME}/.claude/skills"
DESIGNER_DST="${SKILLS_DST}/designer"

echo "[octools] Installing designer skill -> ${DESIGNER_DST}"
mkdir -p "$SKILLS_DST"
rm -rf "$DESIGNER_DST"
cp -R "${TOOLS_DIR}/skills/designer" "$DESIGNER_DST"

# Node deps (sharp, etc.). Skip if already present (e.g. warm container cache).
if [ ! -d "${DESIGNER_DST}/node_modules" ]; then
  echo "[octools] npm install (designer deps)..."
  (cd "$DESIGNER_DST" && npm install --no-audit --no-fund --silent) \
    || echo "[octools] WARN: npm install failed — sharp-based post-processing may be unavailable."
fi

mkdir -p "${HOME}/.designer"
CRED="${HOME}/.designer/credentials.env"
SA_PATH="${HOME}/.gcp_claude_driver_sa.json"
PROJECT="${GOOGLE_CLOUD_PROJECT:-otchealth-shared-prod}"

# ─── Write the GCP SA key from the one env secret ───────────────────
if [ -n "${GCP_CLAUDE_DRIVER_SA_JSON:-}" ]; then
  printf '%s' "$GCP_CLAUDE_DRIVER_SA_JSON" > "$SA_PATH"
  chmod 600 "$SA_PATH"
  echo "[octools] GCP SA key written to $SA_PATH"
elif [ -f "$SA_PATH" ]; then
  echo "[octools] Using existing SA key at $SA_PATH"
else
  echo "[octools] WARN: GCP_CLAUDE_DRIVER_SA_JSON not set and no key on disk — Vertex AI + Secret Manager unavailable."
fi

# ─── Pull API keys from GCP Secret Manager (override with direct env vars) ──
FETCHED=""
if [ -f "$SA_PATH" ]; then
  echo "[octools] Fetching API keys from Secret Manager (project: $PROJECT)..."
  FETCHED="$(GOOGLE_APPLICATION_CREDENTIALS="$SA_PATH" GOOGLE_CLOUD_PROJECT="$PROJECT" \
    node "${TOOLS_DIR}/setup/fetch-secrets.mjs" 2>/dev/null || true)"
fi
# Direct env vars win over Secret Manager (handy for local dev).
get_key() {  # $1=env name
  local name="$1" direct="${!1:-}"
  if [ -n "$direct" ]; then printf '%s' "$direct"; return; fi
  printf '%s' "$FETCHED" | sed -n "s/^${name}=//p" | head -1
}
OPENAI_KEY="$(get_key OPENAI_API_KEY)"
ELEVEN_KEY="$(get_key ELEVENLABS_API_KEY)"
RECRAFT_KEY="$(get_key RECRAFT_API_KEY)"

# ─── Write ~/.designer/credentials.env ──────────────────────────────
{
  echo "# Auto-generated by otchealth-claude-tools/setup/session-start.sh"
  echo "# Secrets sourced from GCP Secret Manager via the claude-driver SA."
  echo "# RING: NON-PHI ONLY. This SA must never touch a PHI project."
  echo "OPENAI_API_KEY=${OPENAI_KEY}"
  echo "ELEVENLABS_API_KEY=${ELEVEN_KEY}"
  echo "GOOGLE_CLOUD_PROJECT=${PROJECT}"
  echo "GOOGLE_APPLICATION_CREDENTIALS=${SA_PATH}"
  echo "VERTEX_DEFAULT_IMAGEN_MODEL=${VERTEX_DEFAULT_IMAGEN_MODEL:-imagen-4.0-generate-001}"
  echo "VERTEX_DEFAULT_VIDEO_MODEL=${VERTEX_DEFAULT_VIDEO_MODEL:-veo-2.0-generate-001}"
  echo "VERTEX_DEFAULT_LLM_MODEL=${VERTEX_DEFAULT_LLM_MODEL:-gemini-2.5-flash}"
  echo "RECRAFT_API_KEY=${RECRAFT_KEY}"
} > "$CRED"
chmod 600 "$CRED"

[ -n "$OPENAI_KEY" ] && echo "[octools] OPENAI_API_KEY: loaded" || echo "[octools] WARN: OPENAI_API_KEY missing (create 'openai-api-key' secret)."
[ -n "$ELEVEN_KEY" ] && echo "[octools] ELEVENLABS_API_KEY: loaded" || echo "[octools] WARN: ELEVENLABS_API_KEY missing (create 'elevenlabs-api-key' secret)."

echo "[octools] Done. Designer skill ready."
echo "[octools] Credentials: $CRED"
