#!/usr/bin/env bash
# session-start.sh — installs the OTCHealth designer skill into ~/.claude/skills
# and re-hydrates credentials from environment secrets. Idempotent: safe to run
# at the start of every Claude Code (web) session.
#
# Wire this into each project's Claude Code environment setup script, e.g.:
#   git clone https://github.com/gbgolfmatt/otchealth-claude-tools /tmp/octools \
#     2>/dev/null || (cd /tmp/octools && git pull --ff-only)
#   bash /tmp/octools/setup/session-start.sh
#
# Required environment secrets (set in the Claude Code environment config):
#   OPENAI_API_KEY            DALL-E 3 / GPT-image-1 / GPT-4 Vision
#   ELEVENLABS_API_KEY        voiceover (TTS)
#   GCP_CLAUDE_DRIVER_SA_JSON full JSON of the non-PHI claude-driver SA key
# Optional:
#   GOOGLE_CLOUD_PROJECT (default otchealth-shared-prod), RECRAFT_API_KEY,
#   VERTEX_DEFAULT_IMAGEN_MODEL / _VIDEO_MODEL / _LLM_MODEL

set -euo pipefail

TOOLS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SKILLS_DST="${HOME}/.claude/skills"
DESIGNER_DST="${SKILLS_DST}/designer"

echo "[octools] Installing designer skill -> ${DESIGNER_DST}"
mkdir -p "$SKILLS_DST"
rm -rf "$DESIGNER_DST"
cp -R "${TOOLS_DIR}/skills/designer" "$DESIGNER_DST"

# Node deps (sharp, etc.). Skip if already present (e.g. warm container cache).
if [ ! -d "${DESIGNER_DST}/node_modules" ]; then
  echo "[octools] npm install (designer deps)..."
  (cd "$DESIGNER_DST" && npm install --no-audit --no-fund --silent) \
    || echo "[octools] WARN: npm install failed — sharp-based post-processing may be unavailable."
fi

# ─── Re-hydrate ~/.designer/credentials.env from env secrets ─────────
mkdir -p "${HOME}/.designer"
CRED="${HOME}/.designer/credentials.env"
SA_PATH="${HOME}/.gcp_claude_driver_sa.json"
{
  echo "# Auto-generated by otchealth-claude-tools/setup/session-start.sh"
  echo "# RING: NON-PHI ONLY. This SA must never touch a PHI project."
  echo "OPENAI_API_KEY=${OPENAI_API_KEY:-}"
  echo "ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY:-}"
  echo "GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT:-otchealth-shared-prod}"
  echo "GOOGLE_APPLICATION_CREDENTIALS=${SA_PATH}"
  echo "VERTEX_DEFAULT_IMAGEN_MODEL=${VERTEX_DEFAULT_IMAGEN_MODEL:-imagen-4.0-generate-001}"
  echo "VERTEX_DEFAULT_VIDEO_MODEL=${VERTEX_DEFAULT_VIDEO_MODEL:-veo-2.0-generate-001}"
  echo "VERTEX_DEFAULT_LLM_MODEL=${VERTEX_DEFAULT_LLM_MODEL:-gemini-2.5-flash}"
  echo "RECRAFT_API_KEY=${RECRAFT_API_KEY:-}"
} > "$CRED"
chmod 600 "$CRED"

# ─── Write the GCP SA key from the env secret ───────────────────────
if [ -n "${GCP_CLAUDE_DRIVER_SA_JSON:-}" ]; then
  printf '%s' "$GCP_CLAUDE_DRIVER_SA_JSON" > "$SA_PATH"
  chmod 600 "$SA_PATH"
  echo "[octools] GCP SA key written to $SA_PATH"
else
  echo "[octools] WARN: GCP_CLAUDE_DRIVER_SA_JSON not set — Vertex AI (Imagen/Gemini/Veo) unavailable."
fi

echo "[octools] Done. Designer skill ready."
echo "[octools] Credentials: $CRED"
